volumes:
  postgres-data:


services:
  postgresql:
    container_name: postgresql
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env.local
    ports:
      - "15432:5432"

  cinema-rest-backend:
    container_name: cinema-rest-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.local
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_started