"""Add User

Revision ID: 72aa0df75b91
Revises: 
Create Date: 2024-05-21 00:38:13.169864

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72aa0df75b91"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA USERS")
    op.create_table(
        "user",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="role"), nullable=True),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
        schema="users",
        comment="Table with all users",
    )
    op.create_index(
        op.f("ix_users_user_sid"), "user", ["sid"], unique=True, schema="users"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_sid"), table_name="user", schema="users")
    op.drop_table("user", schema="users")
    op.execute("DROP SCHEMA users")
    # ### end Alembic commands ###
